### ISSUE TITLE
Vimeo on iPad

### ISSUE THREAD

**Issue by ncnkg** [Selz/plyr#183]
Embedded Vimeo Videos can't be played on iPad. Any solution on this?

**Comment by SamPotts** [comment]
I'll look into this ASAP. Sorry for the delay.

**Comment by magicspon** [comment]
Any news on this issue?

**Comment by SamPotts** [comment]
I've been trying to get to the root of it but can't seem to work out what's causing it. It seems to be an issue for YouTube as well. Still looking at it, it's my next priority.

**Comment by kitestudio** [comment]
To fix the issue I removed the CSS:

```
.plyr .plyr__video-embed iframe {
    pointer-events: none;
}
```

The Plyr controls do not function on the iPad.

**Comment by srinivas08** [comment]
Hi,

Can you  make it  pointer-events: auto; . it should work in ipad also.

Thanks,
Srinivas

**Comment by SamPotts** [comment]
There's a reason it's `pointer-events: none` - so that click events don't get to the iframe, using `auto` would be pointless as it's the default value. I'll do some testing but I suspect that won't be the fix. The problem seemed to also effect the YouTube embeds too.

**Comment by srinivas08** [comment]
I agree, hope we will get update soon on the same.Thanks,

**Comment by SamPotts** [comment]
I think I've worked out why this is an issue. It's an iOS limitation of playing videos without user input. As the iframe is treated as a seperate document the click on the parent of the iframe doesn't count (since it calls the API methods). Removing `pointer-events: none` fixes YouTube as that seems to bind to the video container to play but does mean that some changes will have to be made regarding hiding and showing controls on touch rather than play/pause. However, Vimeo doesn't bind to the video container, only their own play/pause button (hidden off screen in plyr) so this won't work unless we just use the vimeo controls for vimeo embeds. Less than ideal. I will keep digging.

**Comment by 0xsven** [comment]
Any news on this?

**Comment by SamPotts** [comment]
I've temporarily disabled support for YouTube and Vimeo on iOS until I can find a way to get them working 100%. It's an iOS limitation currently.

**Comment by gino8080** [comment]
Could be a temp solution adding something like ?

```css
 @media (max-width: 767px) {
      .plyr .plyr__video-embed iframe,
      .plyr__tooltip {
          pointer-events: auto !important;
      }
  }
  
  body.ios,
  body.ipad{
    .plyr .plyr__video-embed iframe,
    .plyr__tooltip {
        pointer-events: auto !important;
    }
  }
```
