### ISSUE TITLE
hideControls option; possibility to hide them on load

### ISSUE THREAD

**Issue by qikkeronline** [Selz/plyr#250]
Would be great if the hideControls would also make sure that the controls are initially invisible as well. Or an extra option for that maybe. 

Thanks for considering 👍

**Comment by qikkeronline** [comment]
For other people who are looking to achieve this behaviour: I've worked around it atm like this:

**JS:**

`
    $('.plyr').on('ready', function(event) {

        $(this).addClass('plyr--init-hide-controls');

    }).on('play', function(event) {

        $(this).removeClass('plyr--init-hide-controls');

    });
`

**and CSS:**

`
.plyr--init-hide-controls .plyr__controls {
    opacity: 0;
}
`

**Comment by qikkeronline** [comment]
Actually; this is a far better solution (CSS only):

```
    .plyr--stopped .plyr__controls {

        opacity: 0;

    }
```

**Comment by SamPotts** [comment]
I think this one can be closed now. Good idea with the CSS class hook usage 👍

**Comment by kevnk** [comment]
I would add `pointer-events: none;` as well so you can click on controls even when they're invisible:

```css
.plyr--stopped .plyr__controls {
  opacity: 0;
  pointer-events: none;
}
```

**Comment by kevnk** [comment]
I didn't like having controls hidden always when stopped. I just wanted them hidden until they started playing the video. So my final implementation hides the controls by default on stopped, but then allows you to see the controls as normal (when stopped and on hover) after playing the video:

**js**
```javascript
plyr.setup();
$('.plyr').on('play', function(event) {
  $(this).addClass('plyr--init-play');
});
```

**scss**
```scss
.plyr--stopped {
  .plyr__controls {
    opacity: 0;
    pointer-events: none;
  }
  &.plyr--init-play {
    .plyr__controls {
      opacity: 1;
      pointer-events: inherit;
    }
  }
}
```

**Comment by ashleahhill** [comment]
Found this ticket looking for a configuration option on plyr for this. Just want to point out that the default style for `.plyr__controls` puts `pointer-events: all` on all direct decedents, so in the examples above the styles should be:
```scss
.disable-controls .plyr__controls {
    opacity: 0;
    & > * {
        pointer-events: none;
        cursor: auto;
    }
}
```
